updating github folder for issue template
javascript-shinobis/nike-clone-app pull request #21
Opened 2023-06-24 02:01 UTC by Uzafar90

### Changes followed by this PR

---

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

### To-do before the merge

---

**Dependencies added**:

---

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My commits are clean and follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#examples) style.
- [ ] I have created reusable components wherever possible.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

---

## Screenshots / GIFs (If any):

---

2023-06-27 04:58 UTC, abhimishra01 approved these changes

2023-06-27 04:59 UTC, abhimishra01 requested changes
Can we have this in markdown format?


Something like like this :-


```
for title 

### Some Titile


#### Sub Title

- Point 1
- point 2



### Checklist

- [ ] Debugged locally
- [ ] Nodejs 18 used
- [ ] Checklist 3
- [ ] Checklist 4
- [ ] etc

```

2023-07-02 16:39 UTC, Uzafar90 commented
I've developed a couple of templates that could help you in crafting an issue report or a feature proposal for a new idea. These templates will be accessible whenever you or someone else creates an issue.

I have developed this custom template by using **_.yml_** and .md **_files_**. Some of the inputs are optional but I still created them for the best practices as follows. The only inputs that will be populated are the ones that appear, as I have not marked them as required.

Please let me know if anything you want to remove or adjust.

2023-07-04 17:55 UTC, abhimishra01 commented
> I've developed a couple of templates that could help you in crafting an issue report or a feature proposal for a new idea. These templates will be accessible whenever you or someone else creates an issue.
> 
> I have developed this custom template by using **_.yml_** and .md **_files_**. Some of the inputs are optional but I still created them for the best practices as follows. The only inputs that will be populated are the ones that appear, as I have not marked them as required.
> 
> Please let me know if anything you want to remove or adjust.

awesome, thank you for the PR btw, I haven't seen this feature live , lets get this in and see it working

2023-07-04 17:55 UTC, abhimishra01 approved these changes

2023-07-04 17:55 UTC, merged